---

name: Keep master green

on:
  schedule:
    # run hourly
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rerun-failed-jobs:
    if: github.repository_owner == 'emqx'
    runs-on: ['self-hosted', 'linux', 'x64', 'ephemeral']
    permissions:
      checks: read
      actions: write
    steps:
      - uses: actions/checkout@v3

      - name: run script
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/rerun-failed-checks.py
