name: Run Configuration tests

concurrency:
  group: conftest-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      runner_labels:
        required: true
        type: string
      builder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run_conf_tests:
    runs-on: ${{ fromJSON(inputs.runner_labels) }}
    container: ${{ inputs.builder }}
    env:
      PROFILE: ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
          - emqx-enterprise
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ matrix.profile }}
      - name: extract artifact
        run: |
          unzip -o -q ${{ matrix.profile }}.zip
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: ./scripts/test/check-example-configs.sh
      - run: ./scripts/conf-test/run.sh
      - name: print erlang log
        if: failure()
        run: |
          cat _build/${{ matrix.profile }}/rel/emqx/logs/erlang.log.*
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: failure()
        with:
          name: logs-${{ matrix.profile }}
          path: _build/${{ matrix.profile }}/rel/emqx/logs

