---

name: Manage stale issues

on:
  schedule:
    # run hourly
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: github.repository_owner == 'emqx'
    runs-on: ['self-hosted', 'linux', 'x64', 'ephemeral']
    permissions:
      issues: write
      pull-requests: none

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v6
        with:
          days-before-stale: 7
          days-before-close: 7
          exempt-issue-labels: 'internal,BUG,help wanted,#triage/accepted,#needs-triage,Feature,Enhancement'
          stale-issue-label: "#triage/stale"
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          # we don't want stalebot to analyze pull requests
          only-pr-labels: "ZZZDisabledZZZ"
          operations-per-run: 80

...
