name: Static checks

concurrency:
  group: static-checks-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      runner_labels:
        required: true
        type: string
      builder:
        required: true
        type: string
      ct-matrix:
        required: true
        type: string

env:
  IS_CI: "yes"

permissions:
  contents: read

jobs:
  static_checks:
    runs-on: ${{ fromJSON(inputs.runner_labels) }}
    name: "static_checks (${{ matrix.profile }})"
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.ct-matrix) }}
    container: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-ubuntu22.04"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.profile }}
      - name: extract artifact
        run: |
          unzip -o -q ${{ matrix.profile }}.zip
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/cache@v3
        with:
          path: "emqx_dialyzer_${{ matrix.otp }}_plt"
          key: rebar3-dialyzer-plt-${{ matrix.profile }}-${{ matrix.otp }}-${{ hashFiles('rebar.*', 'apps/*/rebar.*', 'lib-ee/*/rebar.*') }}
          restore-keys: |
            rebar3-dialyzer-plt-${{ matrix.profile }}-${{ matrix.otp }}-
      - name: run static checks
        env:
          PROFILE: ${{ matrix.profile }}
        run: make static_checks
